"""从导出的 ONNX 读出每个模型真正需要哪些 --shape，并生成建引擎的 .bat。

权威是我们自己的 ONNX：输入名和静态维以文件里写的为准。社区 onnx2trt.py 的
fitted 档位只作为**同名输入**的参考值（它是给同一份导出脚本的产物用的），
名字对不上就从 dim_param 名推一个，并把静态维不一致的地方报出来。

用法：
  uv run --no-project --with onnx python make_trt_profiles.py [onnx_dir]
"""

import os
import sys

import onnx

ONNX_DIR = sys.argv[1] if len(sys.argv) > 1 else r"C:\workspace\github\nailong-ref\native\gsv\onnx_out"
OUT_BAT = r"C:\workspace\github\nailong-ref\native\gsv\build_engines.bat"
OUT_TRTEXEC = r"C:\workspace\github\nailong-ref\native\gsv\build_engines_trtexec.bat"
ENGINE_DIR = r"C:\workspace\github\nailong-ref\native\gsv\engines"

MODELS = ["ssl", "bert", "vq_encoder", "gpt_encoder", "gpt_step",
          "sovits", "spectrogram", "sv_embedding"]

# onnx2trt.py 的 "fitted" 档位，按输入名索引。audio 因模型而异，单独处理。
FITTED = {
    "input_ids": [(1, 1), (1, 100), (1, 256)],
    "attention_mask": [(1, 1), (1, 100), (1, 256)],
    "token_type_ids": [(1, 1), (1, 100), (1, 256)],
    "phoneme_ids": [(1, 1), (1, 100), (1, 256)],
    "prompts": [(1, 1), (1, 150), (1, 300)],
    "bert_feature": [(1, 1024, 1), (1, 1024, 100), (1, 1024, 256)],
    "samples": [(1, 1), (1, 1), (1, 1)],
    "k_cache": [(24, 1, 1000, 512)] * 3,
    "v_cache": [(24, 1, 1000, 512)] * 3,
    "x_len": [(1,)] * 3,
    "y_len": [(1,)] * 3,
    "idx": [(1,)] * 3,
    "pred_semantic": [(1, 1, 1), (1, 1, 120), (1, 1, 250)],
    "text_seq": [(1, 1), (1, 50), (1, 100)],
    "refer_spec": [(1, 1025, 1), (1, 1025, 280), (1, 1025, 400)],
    "ssl_content": [(1, 768, 50), (1, 768, 300), (1, 768, 700)],
}

# audio 输入各模型采样率/长度不同，按模型给（同样取自 fitted 档位）
AUDIO_BY_MODEL = {
    "ssl": [(1, 16000), (1, 96000), (1, 200000)],
    "spectrogram": [(1, 1), (1, 180000), (1, 400000)],
    "sv_embedding": [(1, 16000), (1, 90000), (1, 180000)],
}

# 动态维没有参考值时的兜底，按 dim_param 名给
DIM_BY_NAME = {"batch_size": 1, "one": 1, "seq_len": 32,
               "text_len": 64, "prompt_len": 64, "sem_len": 64, "ref_len": 64}
FALLBACK = 64


def dynamic_dims(dims):
    """返回动态维的下标；dim_param 是个字符串，静态维是 int。"""
    return [i for i, d in enumerate(dims) if not isinstance(d, int)]


def infer_profile(model_name, input_name, dims):
    """给一个动态输入推 (min, opt, max)。返回 (profile, source)。"""
    candidates = []
    if input_name in FITTED:
        candidates.append((FITTED[input_name], "fitted"))
    if input_name == "audio" and model_name in AUDIO_BY_MODEL:
        candidates.append((AUDIO_BY_MODEL[model_name], "fitted(audio)"))

    ref = None
    source = "inferred"
    for cand, tag in candidates:
        if len(cand[0]) == len(dims):
            ref, source = cand, tag
            break

    if ref is None:
        opt = [d if isinstance(d, int) else DIM_BY_NAME.get(d, FALLBACK) for d in dims]
        ref = [tuple(opt)] * 3

    # 静态维必须与 ONNX 完全一致，所以在档位里把静态维强制取 ONNX 的值
    fixed = [tuple(dims[i] if isinstance(dims[i], int) else entry[i]
                   for i in range(len(dims))) for entry in ref]
    return fixed, source


def main():
    header = ["@echo off", "REM Generated by make_trt_profiles.py - build one engine per model.",
              'call "%~dp0..\\scripts\\env.bat"', "",
              'set "TRT_PROBE=%~dp0..\\build\\bin\\trt_probe.exe"',
              "set FAILED=0", ""]
    probe_lines = list(header)
    trtexec_lines = list(header)
    tail = ["echo.", "if %FAILED%==1 (echo SOME ENGINES FAILED) else (echo ALL ENGINES BUILT)"]
    problems = []

    print(f"onnx dir: {ONNX_DIR}\n")
    for model in MODELS:
        path = os.path.join(ONNX_DIR, f"{model}.onnx")
        if not os.path.exists(path):
            print(f"### {model}: missing, skipped")
            continue
        graph = onnx.load(path, load_external_data=False).graph

        probe_args = []
        entries = []
        print(f"### {model}")
        for inp in graph.input:
            dims = [d.dim_value if d.HasField("dim_value") else d.dim_param
                    for d in inp.type.tensor_type.shape.dim]
            if not dynamic_dims(dims):
                print(f"  {inp.name:<18} {dims}  static")
                continue
            profile, source = infer_profile(model, inp.name, dims)
            for axis, declared in enumerate(dims):
                if isinstance(declared, int) and profile[0][axis] != declared:
                    problems.append(
                        f"{model}.{inp.name} axis{axis}: ONNX={declared} profile={profile[0][axis]}")
            spec = ":".join("x".join(str(v) for v in entry) for entry in profile)
            probe_args.append(f"--shape {inp.name}={spec}")
            entries.append((inp.name, profile))
            print(f"  {inp.name:<18} {dims}  ->  {spec}   [{source}]")

        probe_lines.append(f'echo === {model} ===')
        probe_lines.append(f'"%TRT_PROBE%" build "{path}" ' + " ".join(probe_args))
        probe_lines.append("if errorlevel 1 set FAILED=1")
        probe_lines.append("")

        # trtexec 的三个形状参数各自是逗号分隔的一整串，不是重复出现
        exe = [f'trtexec --onnx="{path}"']
        if entries:
            for flag, slot in (("--minShapes", 0), ("--optShapes", 1), ("--maxShapes", 2)):
                joined = ",".join(f"{name}:{'x'.join(str(v) for v in prof[slot])}"
                                  for name, prof in entries)
                exe.append(f"{flag}={joined}")
        exe.append(f'--saveEngine="{ENGINE_DIR}\\{model}.engine"')
        trtexec_lines.append(f"echo === {model} ===")
        trtexec_lines.append(" ".join(exe))
        trtexec_lines.append("if errorlevel 1 set FAILED=1")
        trtexec_lines.append("")

    os.makedirs(ENGINE_DIR, exist_ok=True)
    for out_path, body in ((OUT_BAT, probe_lines), (OUT_TRTEXEC, trtexec_lines)):
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(body + tail) + "\n")
        print(f"\nwrote {out_path}")

    if problems:
        print("\n!! static dims disagree between ONNX and the profile:")
        for item in problems:
            print(f"   {item}")
    else:
        print("all static dims consistent.")


if __name__ == "__main__":
    main()
